// Mocks generated by Mockito 5.4.4 from annotations
// in advicer_app/test/domain/usecases/advice_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:advicer_app/data/data_sources/advise_remote_data_source.dart'
    as _i2;
import 'package:advicer_app/data/repositories/advise_repo_impl.dart' as _i4;
import 'package:advicer_app/domain/entities/advise_entity.dart' as _i7;
import 'package:advicer_app/domain/failures/failure.dart' as _i6;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAdviseRemoteDataSource_0 extends _i1.SmartFake
    implements _i2.AdviseRemoteDataSource {
  _FakeAdviseRemoteDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdviseRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdviseRepoImpl extends _i1.Mock implements _i4.AdviseRepoImpl {
  @override
  _i2.AdviseRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeAdviseRemoteDataSource_0(
          this,
          Invocation.getter(#remoteDataSource),
        ),
        returnValueForMissingStub: _FakeAdviseRemoteDataSource_0(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i2.AdviseRemoteDataSource);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.AdviseEntity>> getAdvise() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdvise,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.AdviseEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.AdviseEntity>(
          this,
          Invocation.method(
            #getAdvise,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, _i7.AdviseEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.AdviseEntity>(
          this,
          Invocation.method(
            #getAdvise,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.AdviseEntity>>);
}
